### PR TITLE
Buildsystem

### PR DESCRIPTION
**Pull request by hkaiser**

### CODE REVIEW

**Comment by hkaiser** [comment]
@ct-clmsn please note, that this PR also fixes some genuine (I believe) problems. Please carefully check that I have not broken anything.

**Comment by ct-clmsn** [comment]
@hkaiser thanks for taking time to review parts of the backend. Will look the modifications over and test them later today.

**Comment by hkaiser** [comment]
@ct-clmsn Yay, the backend tests pass now (https://github.com/ct-clmsn/chplx/actions/runs/4525858997/jobs/7970635189)! This can be merged. 

Whenever you have new tests, please add them to the CMakeLists.txt (https://github.com/ct-clmsn/chplx/pull/34/files#diff-82704fcfc55b032adadf90a8a643753b83ebe87d1965825f88b7bff0bf457192R18) and the corresponding `*.cpp.good` and `*.hpp.good` files to that directory that the tests will use to verify whether the generated output is correct.

**Comment by ct-clmsn** [comment]
@hkaiser thank you for cleaning things up and adding the testing functionality; everything looks great!

**Pull request merged**
